test.todo("only authenticated users can create exercise in DB")
test.todo("public exercises can be retrieved")
test.todo("design choice: are exercises recreated for each user or is there one master exercises table")
test.todo("user can add public exercise to their exercises")
test.todo("calculate threshold for exercise")
