test.todo("only authenticated users can create practice in DB")
test.todo("public practices can be retrieved by anyone")
test.todo("private practices can only be retrieved by the user")
test.todo("practices can be graphed")
test.todo("user can practice an exercise")
test.todo("user can practice a song")